# Generated by Django 5.0 on 2024-02-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_img',
            field=models.ImageField(blank=True, default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='work_des',
            field=models.TextField(blank=True),
        ),
    ]
